#!/usr/bin/env node
/**
 * Asset scaffolding.
 *
 * The original challenge binaries are not available in this repository, so this script
 * materialises the exact directory tree and filenames the project requires, filled with
 * valid-but-trivial placeholders:
 *
 *   .png  -> 1x1 transparent PNG
 *   .wav  -> valid 8-bit mono PCM WAV containing 1 ms of silence (see note below)
 *   .json/.xml/.txt/.svg -> minimal well-formed documents
 *
 * Design rules:
 *   - Idempotent and NON-destructive: existing files are never overwritten, so dropping the
 *     real assets into `public/assets/` simply wins. Use `--force` to regenerate placeholders.
 *   - It also emits `src/generated/asset-manifest.json`, which the PixiJS loader consumes so
 *     the game is built on the generated structure rather than hardcoded paths.
 *
 * Usage:  node scripts/generate-assets.js [--force] [--check] [--quiet]
 *   --check  create nothing, exit 1 if any declared asset is missing (useful in CI)
 *
 * NOTE on WAV: a literal 0-byte .wav makes `decodeAudioData` / <audio> fail, which would turn
 * every placeholder sound into a loader error. A header + 1 ms of silence is 52 bytes, still
 * "empty" for all practical purposes, but decodes cleanly.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { buildAssetPaths, EXPECTED_ASSET_COUNT } from './asset-manifest.js'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const ASSETS_DIR = join(ROOT, 'public', 'assets')
const MANIFEST_FILE = join(ROOT, 'src', 'generated', 'asset-manifest.json')

const args = new Set(process.argv.slice(2))
const FORCE = args.has('--force')
const CHECK = args.has('--check')
const QUIET = args.has('--quiet')
const log = (...m) => QUIET || console.log(...m)

// ---------------------------------------------------------------------------------------
// Placeholder payloads
// ---------------------------------------------------------------------------------------

/** 1x1 transparent RGBA PNG. */
const PNG_1X1 = Buffer.from(
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAC0lEQVR4nGNgAAIAAAUAAXpeqz8AAAAASUVORK5CYII=',
  'base64',
)

/** Minimal valid PCM WAV: mono, 8 kHz, 8-bit, `samples` frames of silence (0x80). */
function silentWav(samples = 8) {
  const header = Buffer.alloc(44)
  header.write('RIFF', 0, 'ascii')
  header.writeUInt32LE(36 + samples, 4)
  header.write('WAVE', 8, 'ascii')
  header.write('fmt ', 12, 'ascii')
  header.writeUInt32LE(16, 16) // fmt chunk size
  header.writeUInt16LE(1, 20) // PCM
  header.writeUInt16LE(1, 22) // mono
  header.writeUInt32LE(8000, 24) // sample rate
  header.writeUInt32LE(8000, 28) // byte rate
  header.writeUInt16LE(1, 32) // block align
  header.writeUInt16LE(8, 34) // bits per sample
  header.write('data', 36, 'ascii')
  header.writeUInt32LE(samples, 40)
  return Buffer.concat([header, Buffer.alloc(samples, 0x80)])
}

const jsonAtlas = (image, scale) =>
  JSON.stringify(
    {
      frames: {},
      meta: {
        app: 'pirate-battle/scripts/generate-assets',
        version: 'placeholder',
        image,
        format: 'RGBA8888',
        size: { w: 1, h: 1 },
        scale,
      },
      _placeholder: true,
    },
    null,
    2,
  ) + '\n'

const xmlAtlas = (imagePath) =>
  `<?xml version="1.0" encoding="UTF-8"?>\n<!-- Placeholder generated by scripts/generate-assets.js -->\n<TextureAtlas imagePath="${imagePath}">\n</TextureAtlas>\n`

const SVG_LOGO =
  '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 160 40" role="img" aria-label="Jungle Gaming (placeholder)">' +
  '<rect width="160" height="40" rx="6" fill="#0b1f33"/>' +
  '<text x="80" y="25" text-anchor="middle" font-family="sans-serif" font-size="13" fill="#7fe3c5">JUNGLE GAMING</text>' +
  '</svg>\n'

/** @param {string} relPath @returns {Buffer | string} */
function placeholderFor(relPath) {
  const file = relPath.split('/').pop()
  switch (file) {
    case 'ui_sheet.json':
      return jsonAtlas('ui_sheet.png', '1')
    case 'ui_sheet_retina.json':
      return jsonAtlas('ui_sheet_retina.png', '2')
    case 'tilesheets.txt':
      return '# Placeholder generated by scripts/generate-assets.js\n'
  }
  if (relPath.endsWith('.png')) return PNG_1X1
  if (relPath.endsWith('.wav')) return silentWav()
  if (relPath.endsWith('.xml')) return xmlAtlas(file.replace(/\.xml$/, '.png'))
  if (relPath.endsWith('.svg')) return SVG_LOGO
  throw new Error(`No placeholder strategy for "${relPath}"`)
}

// ---------------------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------------------

const paths = buildAssetPaths()

if (new Set(paths).size !== paths.length) {
  throw new Error('Asset manifest contains duplicate paths.')
}
if (paths.length !== EXPECTED_ASSET_COUNT) {
  throw new Error(
    `Asset manifest drift: expected ${EXPECTED_ASSET_COUNT} assets, built ${paths.length}.`,
  )
}

if (CHECK) {
  const missing = paths.filter((p) => !existsSync(join(ASSETS_DIR, p)))
  if (missing.length > 0) {
    console.error(`Missing ${missing.length} asset(s), e.g. ${missing.slice(0, 5).join(', ')}`)
    process.exit(1)
  }
  log(`All ${paths.length} assets present.`)
  process.exit(0)
}

let created = 0
let skipped = 0

for (const relPath of paths) {
  const target = join(ASSETS_DIR, relPath)
  if (!FORCE && existsSync(target)) {
    skipped++
    continue
  }
  mkdirSync(dirname(target), { recursive: true })
  writeFileSync(target, placeholderFor(relPath))
  created++
}

// Manifest consumed by the PixiJS loader. Only rewritten when content changes (no git churn).
const manifest =
  JSON.stringify(
    {
      $comment: 'Generated by scripts/generate-assets.js. Do not edit by hand.',
      root: '/assets',
      count: paths.length,
      paths,
    },
    null,
    2,
  ) + '\n'

mkdirSync(dirname(MANIFEST_FILE), { recursive: true })
const manifestChanged = !existsSync(MANIFEST_FILE) || readFileSync(MANIFEST_FILE, 'utf8') !== manifest
if (manifestChanged) writeFileSync(MANIFEST_FILE, manifest)

log(
  `[assets] ${paths.length} declared | ${created} created | ${skipped} kept (already present)` +
    ` | manifest ${manifestChanged ? 'updated' : 'unchanged'}`,
)
